36# -*- coding: utf-8 -*-
"""GlobexMatch_AdaptiveEngine (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DfUgESSecT8i2P3ZOaUiNuZ-dxuob-gT

# GlobexMatch - Adaptive Buyer Recommendation Engine
**Flow:**
1. Upload cleaned Excel -> enter Exporter ID
2. See one buyer at a time -> type `y` (accept) or `n` (reject)
3. After 15 buyers -> weights update, rejected re-enter pool
4. Next 15 scored with smarter weights
5. Repeat until pool exhausted or you stop
"""

import subprocess
subprocess.run(['pip', 'install', 'openpyxl', '-q'])
import pandas as pd
import numpy as np

print('Libraries ready')


print('Upload EXIM_Cleaned_GlobexMatch.xlsx')
CLEAN_FILE = r"Brain.exe_A1\clean\EXIM_Cleaned_GlobexMatch.xlsx"
print('Loaded:', CLEAN_FILE)

DEFAULT_WEIGHTS = {
    "D1_Product_Compat":  0.30,
    "D2_Geography_Fit":   0.20,
    "D3_Trade_Capacity":  0.20,
    "D4_Intent_Activity": 0.20,
    "D5_Reliability":     0.10,
}
LEARNING_RATE   = 0.05
WEIGHT_MIN      = 0.05
WEIGHT_MAX      = 0.50
DELTA_THRESHOLD = 0.10
TOP_N           = 7

INDUSTRY_AFFINITY = {
    ("Chemicals","Pharmaceuticals"): 0.7,
    ("Electronics","Solar"):         0.6,
    ("Machinery","Auto Parts"):      0.65,
    ("Machinery","Engineering"):     0.70,
    ("IT Software","Electronics"):   0.5,
}
MATURITY_W = {"Growing":1.0,"Stable":0.7,"New":0.5,"Declining":0.2}
HIGH_EXPORT_STATES = {
    "Gujarat":1.0,"Maharashtra":0.9,"Tamil Nadu":0.85,"Karnataka":0.80,
    "Telangana":0.75,"Delhi":0.70,"Haryana":0.65,"Punjab":0.60,"Rajasthan":0.55,
}
COUNTRY_OPENNESS = {
    "Germany":1.0,"USA":1.0,"Japan":0.95,"UK":0.90,"France":0.90,
    "Netherlands":0.90,"Canada":0.85,"Australia":0.85,"Singapore":0.95,
    "Italy":0.80,"UAE":0.85,
}
BILATERAL = {
    "UAE":0.05,"Australia":0.08,"Japan":0.10,"Singapore":0.08,
    "Germany":0.12,"France":0.12,"Netherlands":0.12,"UK":0.15,
    "Italy":0.13,"Canada":0.15,"USA":0.20
}
TRADE_LAW = {
    "USA":0.25,"UK":0.18,"Germany":0.12,"France":0.12,
    "Netherlands":0.10,"Italy":0.13,"Canada":0.15,"Australia":0.08,
    "Japan":0.10,"Singapore":0.07,"UAE":0.06
}
IND_COUNTRY = {
    "Pharmaceuticals": {"USA":0.35,"Germany":0.25,"France":0.25,"UK":0.28,"Japan":0.40,"Australia":0.22,"Canada":0.28,"Netherlands":0.25,"Italy":0.25,"Singapore":0.15,"UAE":0.12},
    "Medical Devices": {"USA":0.35,"Germany":0.28,"France":0.28,"UK":0.30,"Japan":0.38,"Australia":0.22,"Canada":0.25,"Netherlands":0.28,"Italy":0.28,"Singapore":0.15,"UAE":0.12},
    "Chemicals":       {"Germany":0.30,"France":0.30,"Netherlands":0.28,"Italy":0.30,"UK":0.28,"USA":0.22,"Japan":0.25,"Australia":0.18,"Canada":0.20,"Singapore":0.12,"UAE":0.10},
    "Electronics":     {"Germany":0.20,"France":0.20,"Netherlands":0.20,"Italy":0.20,"UK":0.22,"USA":0.18,"Japan":0.25,"Australia":0.15,"Canada":0.18,"Singapore":0.10,"UAE":0.10},
    "Solar":           {"USA":0.40,"Germany":0.18,"France":0.18,"Netherlands":0.18,"UK":0.20,"Japan":0.15,"Australia":0.12,"Canada":0.20,"Singapore":0.10,"UAE":0.08,"Italy":0.18},
    "Textiles":        {"USA":0.20,"Germany":0.12,"France":0.15,"Netherlands":0.12,"Italy":0.18,"UK":0.15,"Japan":0.12,"Australia":0.10,"Canada":0.15,"Singapore":0.08,"UAE":0.08},
    "IT Software":     {"USA":0.18,"Germany":0.12,"France":0.12,"Netherlands":0.10,"Italy":0.10,"UK":0.12,"Japan":0.15,"Australia":0.10,"Canada":0.12,"Singapore":0.08,"UAE":0.10},
    "Machinery":       {"USA":0.15,"Germany":0.18,"France":0.18,"Netherlands":0.15,"Italy":0.18,"UK":0.18,"Japan":0.20,"Australia":0.12,"Canada":0.15,"Singapore":0.10,"UAE":0.10},
    "Auto Parts":      {"USA":0.20,"Germany":0.18,"France":0.18,"Netherlands":0.15,"Italy":0.18,"UK":0.20,"Japan":0.25,"Australia":0.12,"Canada":0.18,"Singapore":0.10,"UAE":0.10},
    "Engineering":     {"USA":0.15,"Germany":0.15,"France":0.15,"Netherlands":0.12,"Italy":0.15,"UK":0.15,"Japan":0.18,"Australia":0.10,"Canada":0.12,"Singapore":0.08,"UAE":0.08},
}
CERT_MAP = {
    "ISO9001":  ["Machinery","Auto Parts","Engineering","Electronics"],
    "ISO14001": ["Chemicals","Pharmaceuticals","Solar"],
    "FDA":      ["Pharmaceuticals","Medical Devices"],
    "CE":       ["Electronics","Medical Devices","Machinery"],
    "WHO-GMP":  ["Pharmaceuticals"],
    "EU-GMP":   ["Pharmaceuticals","Chemicals"],
    "IEC":      ["Solar","Electronics"],
    "SOC2":     ["IT Software"],
    "GDPR":     ["IT Software"],
    "RoHS":     ["Electronics","Solar"],
    "REACH":    ["Chemicals"],
    "TUV":      ["Machinery","Electronics"],
    "UL":       ["Electronics","Machinery"],
}
COUNTRY_REGION = {
    "Netherlands":"Europe","Italy":"Europe","France":"Europe","Germany":"Europe",
    "UK":"Europe","Canada":"North America","USA":"North America",
    "Australia":"Asia","Singapore":"Asia","Japan":"Asia","UAE":"Middle East",
}
NEWS_IMPACT = {"Low":0.05,"Medium":0.12,"High":0.22}
print("Config loaded")

def normalize(val, mn, mx):
    if mx == mn: return 0.5
    return float(np.clip((val - mn) / (mx - mn), 0, 1))

def recency_score(date_val, ref_date):
    if pd.isna(date_val): return 0.0
    days = (ref_date - pd.Timestamp(date_val)).days
    if days <= 90:    return 1.0
    elif days <= 180: return 0.7
    elif days <= 365: return 0.4
    return 0.1

def normalize_weights(weights):
    w = {k: np.clip(v, WEIGHT_MIN, WEIGHT_MAX) for k, v in weights.items()}
    total = sum(w.values())
    return {k: round(v / total, 4) for k, v in w.items()}

def get_adjacent_industries(industry):
    adj = {}
    for (a, b), sc in INDUSTRY_AFFINITY.items():
        if a == industry:   adj[b] = sc
        elif b == industry: adj[a] = sc
    return adj

def build_news_cache(news_df, lookback_days=90):
    cutoff = news_df["Date"].max() - pd.Timedelta(days=lookback_days)
    recent = news_df[news_df["Date"] >= cutoff]
    cache  = {}
    for country in COUNTRY_REGION.keys():
        for industry in IND_COUNTRY.keys():
            region  = COUNTRY_REGION.get(country, "Global")
            rel     = recent[
                (recent["Region"].isin([region, "Global"])) &
                (recent["Affected_Industry"] == industry)
            ]
            penalty = 0.0
            for _, r in rel.iterrows():
                base = NEWS_IMPACT.get(r["Impact_Level"], 0.05)
                if   r["War_Flag"] == 1:                       penalty += base * 1.5
                elif r["Event_Type"] == "Supply Chain Shock":  penalty += base
                elif r["Event_Type"] == "Tariff Update":       penalty += base
                elif r["Event_Type"] == "Stock Crash":         penalty += base * 0.5
                elif r["Event_Type"] == "Natural Calamity":    penalty += base
                elif r["Event_Type"] == "Trade Agreement":     penalty -= base * 0.5
            cache[(country, industry)] = round(min(max(penalty, 0.0), 0.35), 4)
    return cache

print("Helpers loaded")

def score_pool(exp_row, buyer_pool, mat_lookup, news_cache, cap_norms, ref_date, weights):
    pool = buyer_pool.copy()
    ei   = exp_row["Industry"]
    adj  = get_adjacent_industries(ei)
    target = {ei: 1.0}
    target.update(adj)

    pool = pool[pool["Industry"].isin(target.keys())].copy()
    if pool.empty:
        return pd.DataFrame()

    # D1 Product Compatibility
    pool["sem_score"]   = pool["Industry"].map(target).fillna(0.0)
    exp_cert            = str(exp_row.get("Certification", "None"))
    rel_inds            = CERT_MAP.get(exp_cert, [])
    pool["cert_boost"]  = pool["Industry"].apply(
        lambda ii: 1.0 if ii in rel_inds else (0.4 if target.get(ii, 0) > 0 else 0.0))
    exp_msme            = int(exp_row.get("MSME_Udyam", 0))
    pool["size_compat"] = ((pool["Team_Size"] < 500).astype(int) == exp_msme).astype(float) * 0.3
    pool["D1"]          = (pool["sem_score"]*0.60 + pool["cert_boost"]*0.25 + pool["size_compat"]*0.15).clip(0, 1)

    # D2 Geography Fit
    state_score = HIGH_EXPORT_STATES.get(str(exp_row.get("State", "")), 0.4)
    pool["D2"]  = (
        state_score * 0.50 +
        pool["Country"].map(COUNTRY_OPENNESS).fillna(0.5) * 0.30 +
        float(exp_row.get("Has_Shipment_Value", 0)) * 0.20
    ).clip(0, 1)

    # D3 Trade Capacity
    d3_val = (
        normalize(float(exp_row.get("Shipment_Value_USD", 0)), *cap_norms["Shipment_Value_USD"]) * 0.40 +
        normalize(float(exp_row.get("Quantity_Tons",      0)), *cap_norms["Quantity_Tons"])      * 0.30 +
        normalize(float(exp_row.get("Revenue_Size_USD",   0)), *cap_norms["Revenue_Size_USD"])   * 0.20 +
        normalize(float(exp_row.get("Team_Size",          0)), *cap_norms["Team_Size"])          * 0.10
    )
    pool["D3"] = round(float(d3_val), 4)

    # D4 Intent & Activity
    pool["recency"]       = pool["Date"].apply(lambda d: recency_score(d, ref_date))
    pool["maturity_w"]    = pool["Buyer_ID"].map(mat_lookup).map(MATURITY_W).fillna(0.7)
    pool["Funding_Event"] = pd.to_numeric(pool["Funding_Event"], errors="coerce").fillna(0)
    pool["D4"] = (
        (pool["Intent_Score"]         * 0.30 +
         pool["Prompt_Response"]       * 0.15 +
         pool["Hiring_Growth"]         * 0.15 +
         pool["Engagement_Spike"]      * 0.10 +
         pool["DecisionMaker_Change"]  * 0.10 +
         pool["Funding_Event"]         * 0.10 +
         pool["recency"]               * 0.10) * pool["maturity_w"]
    ).clip(0, 1)

    # D5 Reliability
    exp_has_cert = 1.0 if exp_cert and exp_cert != "None" else 0.0
    exp_payment  = float(exp_row.get("Good_Payment_Terms", 0))
    pool["D5"]   = (
        exp_has_cert                  * 0.25 +
        exp_payment                   * 0.25 +
        pool["Good_Payment_History"]  * 0.30 +
        pool["Response_Probability"]  * 0.20
    ).clip(0, 1)

    # Raw Score with current weights
    pool["Raw_Score"] = (
        pool["D1"] * weights["D1_Product_Compat"]  +
        pool["D2"] * weights["D2_Geography_Fit"]   +
        pool["D3"] * weights["D3_Trade_Capacity"]  +
        pool["D4"] * weights["D4_Intent_Activity"] +
        pool["D5"] * weights["D5_Reliability"]
    )

    # Risk
    pool["S1"] = pool.apply(
        lambda r: BILATERAL.get(r["Country"],0.35)*0.40 +
                  TRADE_LAW.get(r["Country"],0.30)*0.35 +
                  IND_COUNTRY.get(r["Industry"],{}).get(r["Country"],0.15)*0.25, axis=1)
    pool["S2"] = (
        pool["War_Event"]                          * 0.30 +
        pool["Tariff_News"].clip(0,1)              * 0.20 +
        pool["StockMarket_Shock"].clip(0,1)        * 0.15 +
        pool["Natural_Calamity"]                    * 0.10 +
        pool["Currency_Fluctuation"].clip(0,1)     * 0.10 +
        float(exp_row.get("War_Risk",0))            * 0.07 +
        max(float(exp_row.get("Tariff_Impact",0)),0)* 0.05 +
        float(exp_row.get("Natural_Calamity_Risk",0))* 0.03
    ).clip(0,1)
    pool["S3"]            = pool.apply(
        lambda r: news_cache.get((r["Country"], r["Industry"]), 0.0), axis=1)
    pool["Risk_Friction"] = (pool["S1"]*0.40 + pool["S2"]*0.35 + pool["S3"]*0.25).clip(0, 0.60)
    pool["Final_Score"]   = (pool["Raw_Score"] - pool["Risk_Friction"]).clip(0, 1).round(4)
    pool["Risk_Label"]    = pool["Risk_Friction"].apply(
        lambda r: "Low" if r<0.10 else ("Medium" if r<0.20 else ("High" if r<0.35 else "Very High")))
    pool["Match_Type"]    = pool["Industry"].apply(lambda ii: "Primary" if ii == ei else "Adjacent")

    return pool.sort_values("Final_Score", ascending=False).reset_index(drop=True)

print("Scorer loaded")

def adjust_weights(accepted_df, rejected_df, current_weights, round_num):
    new_weights = current_weights.copy()
    log = []
    dim_cols = {
        "D1_Product_Compat":  "D1",
        "D2_Geography_Fit":   "D2",
        "D3_Trade_Capacity":  "D3",
        "D4_Intent_Activity": "D4",
        "D5_Reliability":     "D5",
    }
    for dim_key, col in dim_cols.items():
        avg_acc = accepted_df[col].mean() if len(accepted_df) > 0 else 0.5
        avg_rej = rejected_df[col].mean()  if len(rejected_df) > 0 else 0.5
        delta   = avg_acc - avg_rej
        old_w   = current_weights[dim_key]

        if delta > DELTA_THRESHOLD:
            change, direction = LEARNING_RATE, "INCREASE"
        elif delta < -DELTA_THRESHOLD:
            change, direction = -LEARNING_RATE, "DECREASE"
        else:
            change, direction = 0.0, "UNCHANGED"

        new_weights[dim_key] = old_w + change
        log.append({
            "Dimension": dim_key,
            "Old":       round(old_w, 4),
            "Delta":     round(delta, 4),
            "Direction": direction,
        })

    new_weights = normalize_weights(new_weights)
    return new_weights, log

print("Weight adjuster loaded")

SEP  = "=" * 60
SEP2 = "-" * 60

def print_buyer_card(buyer, card_num, total, round_num):
    print(SEP)
    print(f"  ROUND {round_num}  |  Buyer {card_num} of {total}")
    print(SEP)
    print(f"  Buyer ID    : {buyer['Buyer_ID']}")
    print(f"  Country     : {buyer['Country']}")
    print(f"  Industry    : {buyer['Industry']}  [{buyer['Match_Type']}]")
    print(f"  Channel     : {buyer['Preferred_Channel']}")
    print(SEP2)
    print(f"  Match Score : {buyer['Final_Score']:.4f}")
    print(f"  Risk Label  : {buyer['Risk_Label']}")
    print(SEP2)
    print(f"  SCORE BREAKDOWN")
    print(f"    D1 Product Compat  : {buyer['D1']:.3f}   (weight: {round(current_weights['D1_Product_Compat'],3)})")
    print(f"    D2 Geography Fit   : {buyer['D2']:.3f}   (weight: {round(current_weights['D2_Geography_Fit'],3)})")
    print(f"    D3 Trade Capacity  : {buyer['D3']:.3f}   (weight: {round(current_weights['D3_Trade_Capacity'],3)})")
    print(f"    D4 Intent Activity : {buyer['D4']:.3f}   (weight: {round(current_weights['D4_Intent_Activity'],3)})")
    print(f"    D5 Reliability     : {buyer['D5']:.3f}   (weight: {round(current_weights['D5_Reliability'],3)})")
    print(f"    Risk Friction      : -{buyer['Risk_Friction']:.3f}")
    print(SEP)

def print_round_summary(round_num, n_accepted, n_rejected, new_weights, weight_log, pool_remaining):
    print(SEP)
    print(f"  ROUND {round_num} COMPLETE")
    print(SEP)
    print(f"  Accepted : {n_accepted} buyers  -> added to pipeline")
    print(f"  Rejected : {n_rejected} buyers  -> re-enter pool with new weights")
    print(f"  Pool remaining : {pool_remaining:,} buyers")
    print(SEP2)
    print("  WEIGHT UPDATES")
    print(SEP2)
    arrows = {"INCREASE": "UP  ", "DECREASE": "DOWN", "UNCHANGED": "    "}
    for entry in weight_log:
        new_w  = new_weights[entry["Dimension"]]
        arrow  = arrows.get(entry["Direction"], "    ")
        short  = entry["Dimension"].replace("D1_Product_Compat","D1 Product  ")                                   .replace("D2_Geography_Fit", "D2 Geography")                                   .replace("D3_Trade_Capacity","D3 Capacity ")                                   .replace("D4_Intent_Activity","D4 Intent  ")                                   .replace("D5_Reliability",   "D5 Reliability")
        print(f"  [{arrow}] {short} : {entry['Old']:.4f} -> {new_w:.4f}  (delta={entry['Delta']:+.3f})")
    print(SEP)

def print_final_summary(all_accepted, all_rejected_ids, weight_history, total_rounds, pool_remaining):
    print(SEP)
    print("  SESSION COMPLETE")
    print(SEP)
    print(f"  Total Rounds   : {total_rounds}")
    print(f"  Total Accepted : {len(all_accepted)} buyers")
    print(f"  Total Rejected : {len(all_rejected_ids)} unique buyers")
    print(f"  Pool Remaining : {pool_remaining:,} buyers")
    print(SEP2)
    print("  WEIGHT EVOLUTION")
    print(SEP2)
    wh_df = pd.DataFrame(weight_history)
    print(wh_df.to_string(index=False))
    if all_accepted:
        print(SEP2)
        print("  PIPELINE - ACCEPTED BUYERS")
        print(SEP2)
        for b in all_accepted:
            print(f"  {b['Buyer_ID']}  |  {b['Country']:<15} |  {b['Industry']:<18} |  Score: {b['Final_Score']:.4f}")
    print(SEP)

print("Display functions loaded")

print("Loading dataset...")
clean   = pd.read_excel(CLEAN_FILE, sheet_name=None)
exp_df  = clean["Exporters_Clean"]
imp_df  = clean["Importers_Clean"]
news_df = clean["News_Clean"]
mat_df  = clean["Buyer_Maturity"]

for df in [exp_df, imp_df, news_df]:
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
imp_df["Funding_Event"] = pd.to_numeric(imp_df["Funding_Event"], errors="coerce").fillna(0)

mat_lookup = dict(zip(mat_df["Buyer_ID"], mat_df["Maturity"]))
ref_date   = exp_df["Date"].max()
cap_norms  = {c: (exp_df[c].min(), exp_df[c].max())
              for c in ["Shipment_Value_USD","Quantity_Tons","Revenue_Size_USD","Team_Size"]}

print("Building news risk cache...")
news_cache = build_news_cache(news_df)

print("Data ready")
print(f"  Exporters : {exp_df[exp_df['Is_Latest_Record']==1].shape[0]:,}")
print(f"  Importers : {imp_df[imp_df['Is_Latest_Record']==1].shape[0]:,}")

import time

exporter_id = input("Enter Exporter ID (e.g. EXP_1715): ").strip()
exp_matches = exp_df[exp_df["Exporter_ID"] == exporter_id]

if exp_matches.empty:
    print(f"Exporter {exporter_id} not found.")
else:
    exp_row = exp_matches.iloc[0]
    print(f"Found: {exporter_id} | {exp_row['Industry']} | {exp_row['State']}")

    pool             = imp_df[imp_df["Is_Latest_Record"]==1].copy().reset_index(drop=True)
    current_weights  = DEFAULT_WEIGHTS.copy()
    all_accepted     = []
    all_rejected_ids = set()
    weight_history   = [{"Round": 0, **{k: round(v,4) for k, v in current_weights.items()}}]
    round_num        = 0
    keep_going       = True

    while keep_going and len(pool) > 0:
        round_num += 1

        print(f"Scoring pool ({len(pool):,} buyers)...")
        scored = score_pool(exp_row, pool, mat_lookup, news_cache, cap_norms, ref_date, current_weights)

        if scored.empty:
            print("No more matching buyers in pool.")
            break

        top15 = scored.head(TOP_N).copy()

        round_accepted = []
        round_rejected = []

        for i, (_, buyer) in enumerate(top15.iterrows()):
            print()
            print_buyer_card(buyer, i+1, len(top15), round_num)
            time.sleep(0.3)

            while True:
                ans = input("  Accept or Reject?  [y = Accept  |  n = Reject  |  q = Quit]: ").strip().lower()
                if ans in ("y", "n", "q"):
                    break
                print("  Please enter y, n, or q")

            if ans == "q":
                print("Session ended.")
                keep_going = False
                break
            elif ans == "y":
                print("  -> Accepted. Added to pipeline.")
                round_accepted.append(buyer.to_dict())
            else:
                print("  -> Rejected. Will re-appear with updated weights.")
                round_rejected.append(buyer.to_dict())

        if not keep_going:
            break

        acc_ids     = [b["Buyer_ID"] for b in round_accepted]
        rej_ids     = [b["Buyer_ID"] for b in round_rejected]
        accepted_df = top15[top15["Buyer_ID"].isin(acc_ids)]
        rejected_df = top15[top15["Buyer_ID"].isin(rej_ids)]

        if len(round_accepted) > 0 and len(round_rejected) > 0:
            current_weights, weight_log = adjust_weights(accepted_df, rejected_df, current_weights, round_num)
        else:
            weight_log = [{"Dimension":k,"Old":v,"Delta":0,"Direction":"UNCHANGED"}
                          for k, v in current_weights.items()]

        weight_history.append({"Round": round_num, **{k: round(v,4) for k,v in current_weights.items()}})

        pool = pool[~pool["Buyer_ID"].isin(acc_ids)].copy()
        all_accepted.extend(round_accepted)
        all_rejected_ids.update(rej_ids)

        print()
        print_round_summary(round_num, len(round_accepted), len(round_rejected),
                            current_weights, weight_log, len(pool))

        time.sleep(0.3)
        cont = input("""
  Continue to next round? [y / n]: """).strip().lower()
        if cont != "y":
            keep_going = False

    print()
    print_final_summary(all_accepted, all_rejected_ids, weight_history, round_num, len(pool))